name: PouchDB CI

on:
  push: {}
  pull_request:
    branches: [master]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 10
      - run: npm ci
      - run: npm run eslint

# This job currently works, but fails because of violations.  Consider introducing in future.
#  shellcheck:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          persist-credentials: false
#      - run: sudo apt-get install shellcheck
#      - run: git ls-files '*.sh' | xargs shellcheck

  test:
    # TODO should depend on lint... see if things work first
    #needs: lint
    strategy:
      fail-fast: false
      matrix:
        node: [8, 10] # , 12, 14, 16, 18, 20] newer versions don't compile (leveldown?)
        cmd:
          - COMMAND=unit-tests
          - COMMAND=test-express-minimum
          - CLIENT=node COMMAND=test-pouchdb
          - CLIENT=node SERVER_ARGS=--in-memory COMMAND=test-pouchdb
          - CLIENT=node SERVER_ARGS=--sqlite COMMAND=test-pouchdb
          - CLIENT=node SERVER_ARGS="--level-backend memdown" COMMAND=test-pouchdb

          # Test in firefox/phantomjs running on travis
          - CLIENT=selenium:firefox COMMAND=test-pouchdb
          - CLIENT=selenium:phantomjs COMMAND=test-pouchdb

          # Run the mapreduce tests
          - COMMAND=test-pouchdb TYPE=mapreduce CLIENT=node
          - COMMAND=test-pouchdb TYPE=mapreduce CLIENT=selenium:firefox

          # Test against the couchdb harness
          - COMMAND=test-couchdb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: export ${{ matrix.cmd }}
      - run: npm run $COMMAND
